[package]
name = "arch-sway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
regex = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
