[font]
size = 18

[colors.bright]
black = "0x405860"
blue = "0x6699cc"
cyan = "0x5fb3b3"
green = "0x99c794"
magenta = "0xc594c5"
red = "0xec5f67"
white = "0xadb5c0"
yellow = "0xfac863"

[colors.normal]
black = "0x29414f"
blue = "0x6699cc"
cyan = "0x5fb3b3"
green = "0x99c794"
magenta = "0xc594c5"
red = "0xec5f67"
white = "0x65737e"
yellow = "0xfac863"

[colors.primary]
background = "0x090909"
foreground = "0xdddddd"
